audioviz/urls.py
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path
from django.contrib import admin

from films  import views

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('films/', include('films.urls', namespace='films')),
    path('jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls, name='admin'),
    path('boutique/', TemplateView.as_view(template_name='boutique.html'), name='boutique'),
    path('audioviz/', TemplateView.as_view(template_name='audioviz.html'), name='audioviz'),
    path('Blog/', TemplateView.as_view(template_name='audioviz_Blogger.html'), name='audioviz_blogger'),
    path('blog/', include('blog.urls')), 
    path('summernote/', include('django_summernote.urls')),
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blog/urls.py
from django.urls import re_path

from .views import BlogDetailView, BlogNewListView

urlpatterns = [
                re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<slug>[-_\w]+)/$',
                    BlogDetailView.as_view(),
                    name='blog_detail',
                    ),
                 re_path(r'^$', BlogNewListView.as_view(), name='blog_index'),
            ]

films/urls.py
# Urls de l'application films du site audioviz - nouvelle version
from django.urls import path
from django.views.generic import TemplateView
from . import views
from .decorators import check_recaptcha
app_name = 'films'
urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('home/', views.HomeFilms.as_view(), name='home_films'),
    path('<pk>', views.DetailFilm.as_view(), name='detail'),
    path('contact/', check_recaptcha(views.Contact.as_view()), name='contact'),
    path('contact/thanks/', TemplateView.as_view(template_name='thanks.html'), name='thanks'),
    path('acteur/<int:pk>', views.DetailActeur.as_view(), name='detailacteur'),
]

films/models.py
from django.db import models
from datetime import date
FILM_STATUS = (
    ('ECO', 'En cours'),
    ('TST', 'Publié Tests'),
    ('PUB', 'Publié'),     
    ('ARC', 'Archivé')
)
DIR_PHOTOS = 'images/Photos/'
DIR_AFFICHES = 'images/AffichesFilms/'
TODAY = date.today()
YEAR = TODAY.year
class Genre_Film(models.Model):
    genre = models.CharField('genre', max_length=32, unique=True)

    class Meta:
        verbose_name = "genre"
    def __str__(self):
        return self.genre

class Acteur(models.Model):
    name = models.CharField('nom', max_length=64, unique=True)
    resumeCV = models.TextField("Résumé CV", blank=True)
    photoActeur = models.ImageField("Photo Acteur", upload_to=DIR_PHOTOS, blank=True)
    class Meta:
        verbose_name = "Acteur"
    def __str__(self):
        return self.name

class Role(models.Model):
    name = models.CharField('nom', max_length=64, unique=True)
    description = models.TextField("Description")
    class Meta:
        verbose_name = "Role"
    def __str__(self):
        return self.name

class Video_Type(models.Model):
    name = models.CharField('nom', max_length=40, unique=True)
    def __str__(self):
        return self.name

class Video(models.Model):
    name = models.CharField('nom', max_length=64, unique=True)
    videoType = models.ForeignKey(Video_Type, on_delete=models.CASCADE)
    UrlVideo = models.CharField("URL de la vidéo", max_length=20, blank=True)
    def __str__(self):
        return self.name

class Photo(models.Model):
    name = models.CharField('nom', max_length=60, unique=True)
    photo = models.ImageField("Photo", upload_to=DIR_PHOTOS)
    def __str__(self):
        return self.name

class Film(models.Model):
    title = models.CharField('titre du film', max_length=96, unique=True)
    status = models.CharField(choices=FILM_STATUS, max_length=3, default='ECO')
    genre = models.ForeignKey(Genre_Film, on_delete=models.CASCADE)
    synopsis = models.TextField('synopsis')
    created_at = models.DateTimeField('date de création', auto_now_add=True)
    created_user = models.CharField("utilisateur qui a créé", max_length=32)
    changed_at = models.DateTimeField('date de modification', auto_now_add=True)
    changed_user = models.CharField("utilisateur qui a modifié", max_length=32)
    picture = models.ImageField("Affiche", upload_to=DIR_AFFICHES)
    # acteur = models.ManyToManyField(Acteur, related_name='filmsActeurs', blank=True)
    video = models.ManyToManyField(Video, related_name='filmsVideos', blank=True)
    photo = models.ManyToManyField(Photo, related_name='filmsPhotos', blank=True)
    acteur_role = models.ManyToManyField(Acteur,
        through='Role_Film',
        through_fields=('film', 'acteur', 'role'))
    an_creation = models.IntegerField("Année Création", blank=True, default=YEAR)
    class Meta:
            verbose_name = "film"
    def __str__(self):
        return self.title

class Role_Film(models.Model):
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE, blank=True, default = "")
    acteur = models.ForeignKey(Acteur, on_delete=models.CASCADE, blank=True, default = "")
    roledescription = models.CharField("Role Description", max_length=64, blank=True, default = "")
    class Meta:
        verbose_name = "Rôles des participants dans film"
    def __str__(self):
        return self.roledescription

class Contact(models.Model):
    first_name = models.CharField('Votre prénom', max_length=100)
    name = models.CharField('Votre nom', max_length=100)
    email_address = models.EmailField('Votre adresse email')
    subject = models.CharField('Objet de votre messsage', max_length=100)
    message = models.TextField('Texte de votre message')
    class Meta:
        verbose_name = "Contact"
    def __str__(self):
        return f"{self.first_name} - {self.name}"

films/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = [
            'first_name', 'name', 'email_address', 'subject', 'message'
        ]
        widgets = {
            'message': SummernoteWidget(attrs={'summernote': {'width': '100%', 'height': '300px'}}),
        }

films/views.py
from django.views import generic
from django.http import HttpResponse, HttpResponseRedirect
from django.views import View
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateResponseMixin
from django.db.models import Count
from .models import Film, Role_Film, Acteur, Genre_Film
from blog.models import Post
from .forms import ContactForm
from django.core.mail import send_mail, get_connection

class Contact(generic.FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = 'thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        if self.request.recaptcha_is_valid:
            cd = form.cleaned_data
            # envoi message email 
            # con = get_connection('django.core.mail.backends.console.EmailBackend')
            send_mail(cd['subject'], 
            cd['message'],
            cd.get('email', 'relation@audioviz.fr'),
            ['relation@audioviz.fr'],
            # connection=con,
            fail_silently=False
            )
            form.save()
            return super().form_valid(form)
        return render(self.request, 'contact.html', self.get_context_data())

class HomeFilms(generic.ListView):
    model = Film
    template_name = 'film/home_films.html'
    context_object_name = 'films'
    paginate_by = 36
    compteur = 0
    def get_queryset(self):
        if self.request.GET.get('year_search'):
            year_search  = self.request.GET.get('year_search')
        else:
            year_search = 0
        if  self.request.GET.get('genre_search'):
             genre_search  = self.request.GET.get('genre_search')
        else:
            genre_search = "Tous"
        if self.request.GET.get('query'):
            query  = self.request.GET.get('query')
        else:
            query = "Tous"
        if year_search!=0 and genre_search!="Tous" and query!="Tous":  
            # requête 1     
            queryset = Film.objects.filter(an_creation=year_search).filter(genre_id=genre_search).filter(title__icontains=query).filter(status='PUB').order_by('-an_creation')
        elif year_search!=0 and genre_search!="Tous" and query=="Tous":
            # requête 2 
            queryset = Film.objects.filter(an_creation=year_search).filter(genre_id=genre_search).filter(status='PUB').order_by('-an_creation')
        elif year_search!=0 and genre_search=="Tous" and query=="Tous":
            # requête 3
            queryset = Film.objects.filter(an_creation=year_search).filter(status='PUB').order_by('-an_creation')
        elif year_search!=0 and genre_search=="Tous" and query!="Tous":
            # requête 4
            queryset = Film.objects.filter(an_creation=year_search).filter(title__icontains=query).filter(status='PUB').order_by('-an_creation')
        elif year_search==0 and genre_search!="Tous" and query=="Tous":
            # requête 5
            queryset = Film.objects.filter(genre_id=genre_search).filter(status='PUB').order_by('-an_creation')
        elif year_search==0 and genre_search=="Tous" and query!="Tous":
            # requête 6
            queryset = Film.objects.filter(title__icontains=query).filter(status='PUB').order_by('-an_creation')
        elif year_search==0 and genre_search!="Tous" and query!="Tous":   
            queryset = Film.objects.filter(genre_id=genre_search).filter(title__icontains=query).filter(status='PUB').order_by('-an_creation')
        else:
            queryset = Film.objects.order_by('-an_creation').filter(status='PUB')
        compteur = queryset.count() 
        return queryset

    def get_context_data(self, **kwargs):
        if self.request.GET.get('year_search'):
                year_search  = self.request.GET.get('year_search')
        else:
            year_search = 0
        if  self.request.GET.get('genre_search'):
             genre_search  = self.request.GET.get('genre_search')
        else:
            genre_search = "Tous"
        if self.request.GET.get('query'):
            query  = self.request.GET.get('query')
        else:
            query = "Tous"
        if year_search==0 and genre_search=="Tous" and query=="Tous":
            top_filter = False
        else:
            top_filter = True        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["genres"] = Genre_Film.objects.all()
        context["years"] =  Film.objects.distinct().values('an_creation').order_by('-an_creation')
        if year_search == 0:
            year_return = "Toutes"
        else:
            year_return = str(year_search)
        name_genre = "Tous"
        if genre_search != "Tous":
            genre = Genre_Film.objects.get(id=genre_search)
            name_genre = genre.genre
        context["Filters"] = f"Genre: {name_genre} - Année: {year_return} - Titre: {query}"
        context["TopFilter"] = top_filter
        return context
class Index(generic.ListView):
    model = Film
    template_name = 'film/index.html'
    context_object_name = 'films'
    paginate_by = 18
    
    def get_queryset(self):
        queryset = Film.objects.order_by('-an_creation').filter(status='PUB')
        return queryset
        
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['posts']= Post.objects.all().order_by('-modified')[:4]
        return context
class DetailFilm(generic.DetailView):
    model = Film
    template_name = 'film/detail.html'
    context_object_name = 'film'
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # recherche de l'ID de film pour accéder au modèle Film/Acteur/Role
        pk_URL = self.kwargs.get(self.pk_url_kwarg, None)
        film_current = Film.objects.get(id=pk_URL)
        context['roles_film_Autres'] = Role_Film.objects.filter(film_id=pk_URL).order_by('role').exclude(role_id=1)
        context['roles_film_Acteurs'] = Role_Film.objects.filter(film_id=pk_URL).order_by('role').filter(role_id=1)
        context['suggestions'] = Film.objects.filter(status='PUB').filter(genre_id=film_current.genre_id).order_by('-an_creation')[:4]
        return context

class DetailActeur(generic.DetailView):
    model = Acteur
    template_name = 'film/detailacteur.html'
    context_object_name = 'acteur'
    #  query  = self.request.GET.get('query')
    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        pk_URL = self.kwargs.get(self.pk_url_kwarg, None) 
        context['acteur_films'] = Role_Film.objects.filter(acteur_id=pk_URL).distinct('film_id')
        # recherche de l'ID de film pour accéder au modèle Film/Acteur/Role 
        return context

films/templates/film/Search_films.html
<div class="row d-flex-left m-2 ml-1">
<form  id="searchForm" action="#" method="get" accept-charset="utf-8">
    <div class="input-group btn-group-sm">
            <div class="input-group-prepend">
              <label class="input-group-text bg-nav-film text-white" for="inputGroupSelect01">Genre</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="genre_search">
              <option selected></option>
              {% for genre in genres %}
              <option value="{{ genre.id }}">{{ genre.genre }}</option>
              {% endfor %}
            </select> <!--fin Bouton de filtre  Genre-->
            <div class="input-group-prepend">
              <label class="input-group-text bg-nav-film text-white" for="inputGroupSelect01">Année</label>
            </div>
            <select class="custom-select" id="inputGroupSelect01" name="year_search">
              <option selected>{{ year.an_creation }}</option>
              {% for year in years %}
              <option value="{{ year.an_creation }}">{{ year.an_creation }}</option>
              {% endfor %}
            </select>
            
            <div class="input-group-prepend">
                <label class="input-group-text bg-nav-film text-white" for="inputGroupSelect01">Titre</label>
            </div>
            <input type="search" name="query" placeholder="Rechercher" class="form-control" />
            <div class="input-group-append">
                <button class="btn bg-nav-film text-white"><i class="fas fa-play"></i></button>
            </div>           
    </div>
</form>
</div>

films/templates/film/commun.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>audioviz</title>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-122828698-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-122828698-1');
    </script>
    <meta name="description" content="Cette association a pour objectif : 
    la production/réalisation de : 
    courts, moyens et longs métrages
    clips vidéos
    films institutionnels
    reportages
    Et de renforcer les liens sociaux par la réalisation en équipe d'une œuvre audiovisuelle. " />
    <meta name="keywords" content="audiovisuelle, video, cinema, film, courts métrages, log métrages, recette cuisine, turoriel, pub, web-series, clips, reportages, documentaire, liens sociaux, équipe" />
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

   
   
    <link rel="stylesheet" type="text/css" href="{% static 'film/css/fluid-gallery.css' %}" />
    <link href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'film/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'film/css/film-style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'film/css/blog.css' %}" />
  </head>
  <body style="padding-top:70px; padding-bottom: 70px;">
    <header class="navbar navbar-expand-md navbar-dark bg-nav-film fixed-top">
        <a href="#" class="navbar-brand">
           <img src="{% static 'film/img/logoAudiovizRVB.jpg' %}" alt="Logo" width="36" height="44">
        </a><!--end a.navbar-brand-->
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-content">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar-content">
            <nav class="mr-auto">
               <ul class="navbar-nav">
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link"></a></li>
                    <li class="nav-item"><a href="{% url 'index' %}" class="nav-link"><i class="fas fa-home"></i> Accueil</a></li>
                    <li class="nav-item"><a href= "{% url 'films:home_films' %}" class="nav-link"><i class="fas fa-video"></i> Films</a></li>
                    <li class="nav-item"><a href= "{% url 'blog_index' %}" class="nav-link"><i class="far fa-newspaper"></i> News</a></li>
                   <li class="nav-item"><a href="{% url 'audioviz_blogger' %}" class="nav-link"><i class="fab fa-blogger-b"></i> Blog</a></li>
                   <li class="nav-item"><a href="{% url 'boutique' %}" class="nav-link"><i class="fas fa-shopping-cart"></i> Boutique</a></li>
                   <li class="nav-item"><a href="{% url 'audioviz' %}" class="nav-link"><i class="far fa-comments"></i> À propos de</a></li>

                   <li class="nav-item"><a href="{% url 'films:contact' %}" class="nav-link"><i class="fas fa-envelope"></i> Contact</a></li>
               </ul><!--end ul.navbar-nav-->
            </nav>
            <!-- <a href="https://twitter.com/audioviz" class="nav-link"><i class="fab fa-twitter"></i></a> -->
            <a href="https://www.youtube.com/channel/UCbsFkor2F0BtiVlvGkL0fgQ" class="nav-link"><i class="fab fa-youtube blank"></i></a>
            <a href="https://www.facebook.com/login.php?next=https%3A%2F%2Fwww.facebook.com%2Fhome.php#!/pages/Audioviz-Association/131560096888059" class="nav-link"><i class="fab fa-facebook-f blank"></i></a>
            
        </div><!--end div#navbar-content.navbar-collapse-->
   </header><!--End header.navbar-->
  
<main>

{% block content %}{% endblock %}

</main>



<footer>
        <div class="container-fluid m-3">
            <div class="row img-fluid">
                <div class="col-12 text-center">
                    <p>Copyright &copy; <a href="http://angel-belando.fr" target="_blank">Angel Belando</a> pour <a href="/">Audioviz</a></p>
                </div>
            </div>
        </div>
</footer>

<!-- jQuery -->
<script src="{% static 'film/js/jquery-3.3.1.slim.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'film/js/bootstrap.bundle.min.js' %}"></script>

<!-- fontawesomet -->
<script src="{% static 'film/js/fontawesome-all.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.8.1/baguetteBox.min.js"></script>
<script>
    baguetteBox.run('.tz-gallery');
</script>
</body>
</html>

films/templates/film/detail.html
{% extends 'film/commun.html' %}

{% block content %}

<main class="container-fluid" >
          <article class="m-0">
              <div class="row d-flex"></br>
                <div class="col-sm-12 col-lg-5"">
                <img class="img-fluid rounded float-left d-block mr-4 mt-2 mb-2" src="{{ film.picture.url }}" alt="{{ film.title }}" width="240" height="320"  />
                    <h1 class="h2">{{ film.title }}</h1>
                    <p>{{ film.synopsis|safe }}</p>
                    <!-- <blockquote class="blockquote">
                        <footer class="blockquote-footer">Voici de quoi vous donner envie de voir ce fabuleux film. Bonne projection et à bientôt sur Audioviz.</cite></footer>
                    </blockquote> -->
                    <p>
                    <strong>Genre : </strong>{{ film.genre }}
                    <strong>  Année : </strong>{{ film.an_creation }}
                    <br>
                    <div class="line-height-acteur">
                        {% for role_film_Autres in roles_film_Autres %} 
                        <strong>{{ role_film_Autres.role }} :</strong>
                        <a href="{% url 'films:detailacteur' role_film_Autres.acteur_id  %}">{{ role_film_Autres.acteur }}</a> <br>
                        {% endfor %}   
                       
                        <strong>Acteurs :</strong>
                        {% for role_film_Acteurs in roles_film_Acteurs %} 
    
                            <a href="{% url 'films:detailacteur' role_film_Acteurs.acteur_id  %}">
                            {{ role_film_Acteurs.acteur }}</a>
                      
                        {% endfor %}  
                    </div>
                    
                    </p>
                    {% if film.photo.all %}
                    <div class="row col-12">
      
                          <div class="col-12 rounded border border-primary">
                                 <div class="container-fluid">
                                      <p class="h3 p-2 mb-1 text-center rounded">Galerie de photos</p>
                                      <div class="tz-gallery">                               
                                          <div class="row">
                                              {% for photo in film.photo.all %}
                                              <div class="col-sm-12 col-md-3">
                                                  <a class="lightbox" href="{{ photo.photo.url }}">
                                                      <img src="{{ photo.photo.url }}" alt="{{ photo.name }}">
                                                  </a>
                                              </div>
                                              {% endfor %}
                                          </div>                               
                                      </div>
                                  </div> 
                          </div>           
                      </div> 
                     {% endif %}
                </div>
                <div class=" col-sm-12 col-lg-5">
                    {% for video in film.video.all %} 
                    <div class="row">
                        <div class="col-12">
                            <p class="h4 p-2 mb-1 text-center rounded"">{{ video.name }}</p>
                            <div class="embed-responsive embed-responsive-16by9 float-left">
                            <!-- <iframe width="560" height="315" src="https://www.youtube.com/embed/uX-UslzP_vE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe> -->
                            <iframe  class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.UrlVideo }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                            </div>

                        </div>             
                    </div>    
                    {% endfor %}
                </div> 
                    
                <div class="col-sm-12 col-lg-2">
                      
                            <div class="row">
                              <div class="col-12">
                                    <p class="h3 p-2 mb-1 text-center rounded">Suggestions</p>
                              </div> 
                            </div>
                            {% for suggestion in suggestions %}  
                            {% if suggestion.id != film.id %} 
                            <div class="row">
                            <div class="col-lg-12">
                                    <div class="card d-block">
                                    <a href="/films/{{suggestion.id}}"><img class="card-img-top" src="{{ suggestion.picture.url }}" alt="{{ suggestion.title }}" /> </a>    
                                    </div>         
                            </div> 
                            </div> 
                            
                         
                        {% endif %} 
                        {% endfor %}                   
                </div> 
              </div>

             
          </article>

</main><!--end main.container-fluid-->
{% endblock %}

films/templates/film/detailacteur.html
{% extends 'film/commun.html' %}

{% block content %}

<!-- ------------------------travail -->
<main class="container-fluid mb-4" >
   <section class="row my-4">
       <div class="col-12 col-lg-5">
         
          <article class="mb-3">
                <h1 class="h1">{{ acteur.name }}</h1>
               
                <figure class="figure float-lg-left mr-3">
                    {% if  acteur.photoActeur %}
                    <img src="{{ acteur.photoActeur.url }}" alt="{{ acteur.name }}" class="img-fluid rounded-circle""/>  
                    {% endif %}
                </figure>  
                <p class="p">{{ acteur.resumeCV|safe }}</p>
          </article>
      </div><!--End second column-->
      <div class="col-12 col-lg-7">
            <div class="list-group list-group-flush">
                    {% for acteur_film in acteur_films %}
                    {% if acteur_film.film.status == 'PUB' %}
                    <article class="list-group-item list-group-item-action">
                         <div class="row">
                                <div class="col12 col-md-2">
                                        <a href="{% url 'films:detail' acteur_film.film_id  %}""><img src="{{ acteur_film.film.picture.url }}" class="img-fluid img-thumbnail" alt="{{ post.title }}" ></a> 
                                </div>
                                <div class="col12 col-md-10">
                                           <h1 class="h3">{{ acteur_film.role.name}} dans {{ acteur_film.film.title }}  </h1>
                                           <p>{{ acteur_film.film.synopsis|safe }} </p>

                                </div><!---End second column of Article-->


                                    <!-- 
                                        titre = {{ acteur_film.film.title }} <br>
                                synopsis = {{ acteur_film.film.synopsis}} <br>
                               film_id =  {{ acteur_film.film_id }} <br>
                                picture = {{ acteur_film.film.picture.url }} <br>
                                role_id = {{ acteur_film.role.name}} <br>
                                    -->      
                         </div>
                    </article><!--end article.list-group-item-->
                    {% endif %}
                    {% endfor %}
            </div><!--End div.list-group-->
      </div>
   </section><!--end section.row-->
</main><!--end main.container-fluid-->
{% endblock %}

films/templates/film/home_films.html
{% extends 'film/commun.html' %}
{% block content %}
<div class="bg-image">
    {% include 'film/searchfilms.html' %}
    {% include 'film/listefilms.html' with listefilms_title='Nos derniers films' %}
</div>
  
{% endblock %}

films/templates/film/index.html
{% extends 'film/commun.html' %}

{% block content %}

    {% include 'blog/post_list_news.html' with listefilms_title='Blog' %}
    {% include 'film/listefilms.html' with listefilms_title='Nos derniers films' %}

 
{% endblock %}

films/templates/film/listefilms.html
<div class="bg-image">
    {% if films %}
    <div class="row">
				<div class="col-12">
			
            <div class="text-white h1 text-center">
                <i class="fas fa-video"></i>
               FILMS 
               <i class="fas fa-video"></i>
            </div>
          
				</div>
			</div>
 
  <div class="row ">
  {% for film in films %}
    <!-- films  -->    
        <div class="col-lg-2 col-md-6">
          <div class="card img-fluid mb-3">
            <a href="/films/{{film.id}}"><img src="{{ film.picture.url }}" alt="{{ film.title }}" class="card-img-top" /></a> 
          </div><!--End .card-->
        </div><!--End first element-->   
  {% endfor %}
      </div><!--End section.row third row-->  
{% else %}
  <div class="text-center">
    Pas de film
  </div>
{% endif %}


<!--Begin Bottom pagination - Mise en forme-->
{% if is_paginated %}
<nav>
<ul class="pagination justify-content-center">
  {% if page_obj.has_previous %}
    <li class="page-item "><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo;</a></li>
  {% endif %}
  {% for i in page_obj.paginator.page_range %}
    {% if page_obj.number == i %}
      <li class="page-item active"><a href="#" class="page-link">{{ page_obj.number }}</a></li>
    {% else %}
      <li class="page-item" ><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if page_obj.has_next %}
    <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link">&raquo;</a></li>
  {% endif %}
</ul>
</nav>
{% endif %}

</div>